


/***CONEXION DESDE EL FRONT AL PUERTO DE SALIDA DEL BACKEND***/
module.exports = {
    api:{
        baseURL: 'https://onlyfortestingapimulticomerciales.online'/**PUERTO 4000 => ES LA PUERTA DE CONEXION CON EL BACK */
        /**PARA QUE EL FRONTEND SE PUEDA CONECTAR CON EL BACKEND, OBLIGATORIAMENTE DEBEN DE ESTABLECER
         *COMUNICACION POR EL MISMO PUERTO => EN ESTE CASO: 4000
         * **/
    }
}